defaults:
  - default

_target_: tracklab.wrappers.ExternalVideo

video_path: "${project_dir}/docs/assets/example_dancetrack0058.mp4"
# video_path: "https://youtu.be/B_1Ifzf0ayA"    #SN-GS021
# video_path: "/home/student/headers-tracking/my_gamestate/SNGS-021_video.mp4" #SN-GS021


# This didnt change for the tracking pose, try with bbox
youtube_params:
  format: "bestvideo[height<=1080]+bestaudio/best[height<=1080]"  # Limit to 1080p
  socket_timeout: 60  # Increase timeout
  retries: 3  # Add retries for more reliable downloads

